plugins:
  «Restrict_Files»_Enabled:
    default: false
    client: true
  «Restrict_Files»_Access_List_Type:
    enum: 'RestrictFiles_AccessListType'
    default: 'whitelist'
    client: true
  «Restrict_Files»_Access_List:
    client: true
    type: list
    default: 'admins|moderators|staff'
  «Restrict_Files»_Mesage_To_Unauthenticated:
    default: "A message to unauthenticated (anonymous, not logged in) users.<br/>You can use <b>HTML tags</b> here, including a link to a payment page.<br/>To receive payments you can use <a href='https://discourse.pro/t/29'>PayPal Buy Now</a> plugin."
    client: true
  «Restrict_Files»_Mesage_To_Unauthorized:
    default: "A message to unauthorized users.<br/>You can use <b>HTML tags</b> here, including a link to a payment page.<br/>To receive payments you can use <a href='https://discourse.pro/t/29'>PayPal Buy Now</a> plugin."
    client: true
